//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("carserviceModel", "FK_customerVehicle", "Customers", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(VehicleRepair.DAL.Customer), "vehicles", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(VehicleRepair.DAL.Vehicle), true)]
[assembly: EdmRelationshipAttribute("carserviceModel", "FK_PhoneNumbers_Customers", "Customers", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(VehicleRepair.DAL.Customer), "PhoneNumbers", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(VehicleRepair.DAL.PhoneNumber), true)]
[assembly: EdmRelationshipAttribute("carserviceModel", "FK_vehicles_vehicleService", "Vehicle", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(VehicleRepair.DAL.Vehicle), "vehicleService", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(VehicleRepair.DAL.VehicleService), true)]

#endregion

namespace VehicleRepair.DAL
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class VehicleEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new VehicleEntities object using the connection string found in the 'VehicleEntities' section of the application configuration file.
        /// </summary>
        public VehicleEntities() : base("name=VehicleEntities", "VehicleEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new VehicleEntities object.
        /// </summary>
        public VehicleEntities(string connectionString) : base(connectionString, "VehicleEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new VehicleEntities object.
        /// </summary>
        public VehicleEntities(EntityConnection connection) : base(connection, "VehicleEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Customer> Customers
        {
            get
            {
                if ((_Customers == null))
                {
                    _Customers = base.CreateObjectSet<Customer>("Customers");
                }
                return _Customers;
            }
        }
        private ObjectSet<Customer> _Customers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PhoneNumber> PhoneNumbers
        {
            get
            {
                if ((_PhoneNumbers == null))
                {
                    _PhoneNumbers = base.CreateObjectSet<PhoneNumber>("PhoneNumbers");
                }
                return _PhoneNumbers;
            }
        }
        private ObjectSet<PhoneNumber> _PhoneNumbers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Vehicle> Vehicles
        {
            get
            {
                if ((_Vehicles == null))
                {
                    _Vehicles = base.CreateObjectSet<Vehicle>("Vehicles");
                }
                return _Vehicles;
            }
        }
        private ObjectSet<Vehicle> _Vehicles;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<VehicleService> VehicleServices
        {
            get
            {
                if ((_VehicleServices == null))
                {
                    _VehicleServices = base.CreateObjectSet<VehicleService>("VehicleServices");
                }
                return _VehicleServices;
            }
        }
        private ObjectSet<VehicleService> _VehicleServices;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Customers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCustomers(Customer customer)
        {
            base.AddObject("Customers", customer);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PhoneNumbers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPhoneNumbers(PhoneNumber phoneNumber)
        {
            base.AddObject("PhoneNumbers", phoneNumber);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Vehicles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToVehicles(Vehicle vehicle)
        {
            base.AddObject("Vehicles", vehicle);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the VehicleServices EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToVehicleServices(VehicleService vehicleService)
        {
            base.AddObject("VehicleServices", vehicleService);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="carserviceModel", Name="Customer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Customer : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Customer object.
        /// </summary>
        /// <param name="customerID">Initial value of the customerID property.</param>
        /// <param name="firstName">Initial value of the firstName property.</param>
        /// <param name="lastName">Initial value of the lastName property.</param>
        /// <param name="city">Initial value of the city property.</param>
        /// <param name="state">Initial value of the state property.</param>
        public static Customer CreateCustomer(global::System.Int32 customerID, global::System.String firstName, global::System.String lastName, global::System.String city, global::System.String state)
        {
            Customer customer = new Customer();
            customer.customerID = customerID;
            customer.firstName = firstName;
            customer.lastName = lastName;
            customer.city = city;
            customer.state = state;
            return customer;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 customerID
        {
            get
            {
                return _customerID;
            }
            set
            {
                if (_customerID != value)
                {
                    OncustomerIDChanging(value);
                    ReportPropertyChanging("customerID");
                    _customerID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("customerID");
                    OncustomerIDChanged();
                }
            }
        }
        private global::System.Int32 _customerID;
        partial void OncustomerIDChanging(global::System.Int32 value);
        partial void OncustomerIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String firstName
        {
            get
            {
                return _firstName;
            }
            set
            {
                OnfirstNameChanging(value);
                ReportPropertyChanging("firstName");
                _firstName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("firstName");
                OnfirstNameChanged();
            }
        }
        private global::System.String _firstName;
        partial void OnfirstNameChanging(global::System.String value);
        partial void OnfirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String lastName
        {
            get
            {
                return _lastName;
            }
            set
            {
                OnlastNameChanging(value);
                ReportPropertyChanging("lastName");
                _lastName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("lastName");
                OnlastNameChanged();
            }
        }
        private global::System.String _lastName;
        partial void OnlastNameChanging(global::System.String value);
        partial void OnlastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String adress
        {
            get
            {
                return _adress;
            }
            set
            {
                OnadressChanging(value);
                ReportPropertyChanging("adress");
                _adress = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("adress");
                OnadressChanged();
            }
        }
        private global::System.String _adress;
        partial void OnadressChanging(global::System.String value);
        partial void OnadressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String city
        {
            get
            {
                return _city;
            }
            set
            {
                OncityChanging(value);
                ReportPropertyChanging("city");
                _city = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("city");
                OncityChanged();
            }
        }
        private global::System.String _city;
        partial void OncityChanging(global::System.String value);
        partial void OncityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String state
        {
            get
            {
                return _state;
            }
            set
            {
                OnstateChanging(value);
                ReportPropertyChanging("state");
                _state = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("state");
                OnstateChanged();
            }
        }
        private global::System.String _state;
        partial void OnstateChanging(global::System.String value);
        partial void OnstateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String postCode
        {
            get
            {
                return _postCode;
            }
            set
            {
                OnpostCodeChanging(value);
                ReportPropertyChanging("postCode");
                _postCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("postCode");
                OnpostCodeChanged();
            }
        }
        private global::System.String _postCode;
        partial void OnpostCodeChanging(global::System.String value);
        partial void OnpostCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("carserviceModel", "FK_customerVehicle", "vehicles")]
        public EntityCollection<Vehicle> vehicles
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Vehicle>("carserviceModel.FK_customerVehicle", "vehicles");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Vehicle>("carserviceModel.FK_customerVehicle", "vehicles", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("carserviceModel", "FK_PhoneNumbers_Customers", "PhoneNumbers")]
        public EntityCollection<PhoneNumber> PhoneNumbers
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PhoneNumber>("carserviceModel.FK_PhoneNumbers_Customers", "PhoneNumbers");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PhoneNumber>("carserviceModel.FK_PhoneNumbers_Customers", "PhoneNumbers", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="carserviceModel", Name="PhoneNumber")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PhoneNumber : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PhoneNumber object.
        /// </summary>
        /// <param name="phoneType">Initial value of the phoneType property.</param>
        /// <param name="number">Initial value of the number property.</param>
        /// <param name="customerID">Initial value of the customerID property.</param>
        public static PhoneNumber CreatePhoneNumber(global::System.String phoneType, global::System.String number, global::System.Int32 customerID)
        {
            PhoneNumber phoneNumber = new PhoneNumber();
            phoneNumber.phoneType = phoneType;
            phoneNumber.number = number;
            phoneNumber.customerID = customerID;
            return phoneNumber;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String phoneType
        {
            get
            {
                return _phoneType;
            }
            set
            {
                if (_phoneType != value)
                {
                    OnphoneTypeChanging(value);
                    ReportPropertyChanging("phoneType");
                    _phoneType = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("phoneType");
                    OnphoneTypeChanged();
                }
            }
        }
        private global::System.String _phoneType;
        partial void OnphoneTypeChanging(global::System.String value);
        partial void OnphoneTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String number
        {
            get
            {
                return _number;
            }
            set
            {
                if (_number != value)
                {
                    OnnumberChanging(value);
                    ReportPropertyChanging("number");
                    _number = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("number");
                    OnnumberChanged();
                }
            }
        }
        private global::System.String _number;
        partial void OnnumberChanging(global::System.String value);
        partial void OnnumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 customerID
        {
            get
            {
                return _customerID;
            }
            set
            {
                if (_customerID != value)
                {
                    OncustomerIDChanging(value);
                    ReportPropertyChanging("customerID");
                    _customerID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("customerID");
                    OncustomerIDChanged();
                }
            }
        }
        private global::System.Int32 _customerID;
        partial void OncustomerIDChanging(global::System.Int32 value);
        partial void OncustomerIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("carserviceModel", "FK_PhoneNumbers_Customers", "Customers")]
        public Customer Customer
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Customer>("carserviceModel.FK_PhoneNumbers_Customers", "Customers").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Customer>("carserviceModel.FK_PhoneNumbers_Customers", "Customers").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Customer> CustomerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Customer>("carserviceModel.FK_PhoneNumbers_Customers", "Customers");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Customer>("carserviceModel.FK_PhoneNumbers_Customers", "Customers", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="carserviceModel", Name="Vehicle")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Vehicle : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Vehicle object.
        /// </summary>
        /// <param name="registration">Initial value of the registration property.</param>
        /// <param name="make">Initial value of the make property.</param>
        /// <param name="model">Initial value of the model property.</param>
        /// <param name="type">Initial value of the type property.</param>
        /// <param name="year">Initial value of the year property.</param>
        public static Vehicle CreateVehicle(global::System.String registration, global::System.String make, global::System.String model, global::System.String type, global::System.Int16 year)
        {
            Vehicle vehicle = new Vehicle();
            vehicle.registration = registration;
            vehicle.make = make;
            vehicle.model = model;
            vehicle.type = type;
            vehicle.year = year;
            return vehicle;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String registration
        {
            get
            {
                return _registration;
            }
            set
            {
                if (_registration != value)
                {
                    OnregistrationChanging(value);
                    ReportPropertyChanging("registration");
                    _registration = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("registration");
                    OnregistrationChanged();
                }
            }
        }
        private global::System.String _registration;
        partial void OnregistrationChanging(global::System.String value);
        partial void OnregistrationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String make
        {
            get
            {
                return _make;
            }
            set
            {
                OnmakeChanging(value);
                ReportPropertyChanging("make");
                _make = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("make");
                OnmakeChanged();
            }
        }
        private global::System.String _make;
        partial void OnmakeChanging(global::System.String value);
        partial void OnmakeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String model
        {
            get
            {
                return _model;
            }
            set
            {
                OnmodelChanging(value);
                ReportPropertyChanging("model");
                _model = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("model");
                OnmodelChanged();
            }
        }
        private global::System.String _model;
        partial void OnmodelChanging(global::System.String value);
        partial void OnmodelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String type
        {
            get
            {
                return _type;
            }
            set
            {
                OntypeChanging(value);
                ReportPropertyChanging("type");
                _type = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("type");
                OntypeChanged();
            }
        }
        private global::System.String _type;
        partial void OntypeChanging(global::System.String value);
        partial void OntypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 year
        {
            get
            {
                return _year;
            }
            set
            {
                OnyearChanging(value);
                ReportPropertyChanging("year");
                _year = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("year");
                OnyearChanged();
            }
        }
        private global::System.Int16 _year;
        partial void OnyearChanging(global::System.Int16 value);
        partial void OnyearChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String color
        {
            get
            {
                return _color;
            }
            set
            {
                OncolorChanging(value);
                ReportPropertyChanging("color");
                _color = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("color");
                OncolorChanged();
            }
        }
        private global::System.String _color;
        partial void OncolorChanging(global::System.String value);
        partial void OncolorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String vin
        {
            get
            {
                return _vin;
            }
            set
            {
                OnvinChanging(value);
                ReportPropertyChanging("vin");
                _vin = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("vin");
                OnvinChanged();
            }
        }
        private global::System.String _vin;
        partial void OnvinChanging(global::System.String value);
        partial void OnvinChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String capacity
        {
            get
            {
                return _capacity;
            }
            set
            {
                OncapacityChanging(value);
                ReportPropertyChanging("capacity");
                _capacity = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("capacity");
                OncapacityChanged();
            }
        }
        private global::System.String _capacity;
        partial void OncapacityChanging(global::System.String value);
        partial void OncapacityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String fuelType
        {
            get
            {
                return _fuelType;
            }
            set
            {
                OnfuelTypeChanging(value);
                ReportPropertyChanging("fuelType");
                _fuelType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("fuelType");
                OnfuelTypeChanged();
            }
        }
        private global::System.String _fuelType;
        partial void OnfuelTypeChanging(global::System.String value);
        partial void OnfuelTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> customerID
        {
            get
            {
                return _customerID;
            }
            set
            {
                OncustomerIDChanging(value);
                ReportPropertyChanging("customerID");
                _customerID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("customerID");
                OncustomerIDChanged();
            }
        }
        private Nullable<global::System.Int32> _customerID;
        partial void OncustomerIDChanging(Nullable<global::System.Int32> value);
        partial void OncustomerIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("carserviceModel", "FK_customerVehicle", "Customers")]
        public Customer Customer
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Customer>("carserviceModel.FK_customerVehicle", "Customers").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Customer>("carserviceModel.FK_customerVehicle", "Customers").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Customer> CustomerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Customer>("carserviceModel.FK_customerVehicle", "Customers");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Customer>("carserviceModel.FK_customerVehicle", "Customers", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("carserviceModel", "FK_vehicles_vehicleService", "vehicleService")]
        public EntityCollection<VehicleService> vehicleServices
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<VehicleService>("carserviceModel.FK_vehicles_vehicleService", "vehicleService");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<VehicleService>("carserviceModel.FK_vehicles_vehicleService", "vehicleService", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="carserviceModel", Name="VehicleService")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class VehicleService : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new VehicleService object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="subject">Initial value of the subject property.</param>
        /// <param name="registration">Initial value of the registration property.</param>
        public static VehicleService CreateVehicleService(global::System.Int32 id, global::System.String subject, global::System.String registration)
        {
            VehicleService vehicleService = new VehicleService();
            vehicleService.id = id;
            vehicleService.subject = subject;
            vehicleService.registration = registration;
            return vehicleService;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String subject
        {
            get
            {
                return _subject;
            }
            set
            {
                OnsubjectChanging(value);
                ReportPropertyChanging("subject");
                _subject = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("subject");
                OnsubjectChanged();
            }
        }
        private global::System.String _subject;
        partial void OnsubjectChanging(global::System.String value);
        partial void OnsubjectChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> odometer
        {
            get
            {
                return _odometer;
            }
            set
            {
                OnodometerChanging(value);
                ReportPropertyChanging("odometer");
                _odometer = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("odometer");
                OnodometerChanged();
            }
        }
        private Nullable<global::System.Int32> _odometer;
        partial void OnodometerChanging(Nullable<global::System.Int32> value);
        partial void OnodometerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> serviceDate
        {
            get
            {
                return _serviceDate;
            }
            set
            {
                OnserviceDateChanging(value);
                ReportPropertyChanging("serviceDate");
                _serviceDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("serviceDate");
                OnserviceDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _serviceDate;
        partial void OnserviceDateChanging(Nullable<global::System.DateTime> value);
        partial void OnserviceDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String registration
        {
            get
            {
                return _registration;
            }
            set
            {
                OnregistrationChanging(value);
                ReportPropertyChanging("registration");
                _registration = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("registration");
                OnregistrationChanged();
            }
        }
        private global::System.String _registration;
        partial void OnregistrationChanging(global::System.String value);
        partial void OnregistrationChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("carserviceModel", "FK_vehicles_vehicleService", "Vehicle")]
        public Vehicle vehicle
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Vehicle>("carserviceModel.FK_vehicles_vehicleService", "Vehicle").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Vehicle>("carserviceModel.FK_vehicles_vehicleService", "Vehicle").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Vehicle> vehicleReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Vehicle>("carserviceModel.FK_vehicles_vehicleService", "Vehicle");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Vehicle>("carserviceModel.FK_vehicles_vehicleService", "Vehicle", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
